# Generated by Django 5.2.4 on 2025-08-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationupdate',
            name='device_id',
            field=models.CharField(default='id_not_found'),
        ),
    ]
